# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
from = '/*'
to = 'https://api.intern.d-tt.nl/api/*'
status = 200
[[redirects]]
from = '/*'
to = '/index.html'
status = 200